### ISSUE TITLE
이벤트 소싱 부분 작성하신건가요??

### ISSUE THREAD

**Issue by audtjddld** [devsejong/SimpleEventHandler#1]
최범균님의 DDD-start 보시고 거의 마지막에 나오는 event sourcing 부분이 맞는지 궁금합니다.
잘 이해가 안되는 부분도 있어서 ㅎㅎ

**Comment by devsejong** [comment]
작업의 변경이 일어났을때 이벤트를 보내주도록 만들어놓은 코드예요. 이벤트드리븐아니면 반응형프로그래밍(??)에 가깝지 않을까 싶네요. (아직 저부분은 잘 몰라서.. 맞는지는 모르겠어요)

최범균님이 활용한 방법은 순수한 자바를 활용해서 스프링과 연결하기가 쉽지 않은 문제가 있어서 고민하다가 만들어본 예제였습니다.
제가 만든것과 비슷한 기능이 스프링 4.2에서 추가되는 바람에 지금은 그걸써서 작업하고 있습니다. https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2

**Comment by devsejong** [comment]
현재의 상태가 아니라 이벤트 자체를 저장하는것이 아마 이벤트 소싱으로 알고 있어요.
https://blog.weirdx.io/post/37496

**Comment by audtjddld** [comment]
@devsejong 답변 감사합니다 ㅎㅎ 4.2에서 추가되었었네요 
이벤트 소싱 부분을 최범균님 책보고 해볼려고 하니 대략적으로만 이해가되어서 
혹시 좀더 쉽게 이해할 수 있는 코드가 있는지 싶었습니다.
저도 공유해주신 링크 확인해보겠습니다.

**Comment by devsejong** [comment]
좋은 예제가 아니라서.. 많이 부끄럽네요.

책을 보고있는데, 최범균님의 책에선 이벤트 소싱이 아닌것 같아요.
이벤트소싱은 이벤트자체를 저장하고 조회시엔 하나로 합쳐서 정보를 가져오는거라서요.

이벤트 자체가 발생하면 다른 도메인에 전달되어 약한결합으로 프로그램을 구성할 수 있다가 지금 코드와 책의 내용입니다. 즉 이벤트라는게 단순히 다른 로직을 실행시켜주는 역할로써만 사용합니다.
반면에 이벤트 소싱은 이벤트자체 저장하고 이를 기준으로 데이터를 조회하는데 활용해요. 즉 이벤트가 가장 중요한 데이터로 사라지거나 수정되어서는 안되는 것이 됩니다.

**Comment by audtjddld** [comment]
@devsejong 이벤트 소싱 관련 설명하는 글 봤을때 발생된 이벤트를 누적 시켜서 가지고 있는 그림을 본것 같은데 제가 잘못 이해하고 있었네요 ㅎㅎ 감사합니다.
